### ISSUE TITLE
How to reg func type ?

### ISSUE THREAD

**Issue by nzlov** [dearplain/goloader#12]
[DEMO](https://github.com/nzlov/testgoloader)
When load 'a.o', output :
```
panic: unresolve external: type.github.com/gin-gonic/gin.HandlerFunc
```

**Comment by dearplain** [comment]
try
```
goloader.RegTypes(symPtr, gin.HandlerFunc)
```

**Comment by nzlov** [comment]
Don't work...
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x119ee3d]

goroutine 1 [running]:
github.com/dearplain/goloader.regTypeInfo(0xc4203af650, 0x1628460, 0x0, 0x13)
	/Users/nzlov/workspace/go/src/github.com/dearplain/goloader/type.go:121 +0x8d
github.com/dearplain/goloader.RegTypes(0xc4203af650, 0xc4205f7ef8, 0x1, 0x1)
	/Users/nzlov/workspace/go/src/github.com/dearplain/goloader/type.go:105 +0xa4
main.genSymPtr()
	/Users/nzlov/workspace/go/src/github.com/nzlov/testgoloader/main.go:50 +0xc6
main.main()
	/Users/nzlov/workspace/go/src/github.com/nzlov/testgoloader/main.go:21 +0x44
exit status 2
```

**Comment by dearplain** [comment]
try again. @nzlov

**Comment by nzlov** [comment]
Thanks,It good work.
