### ISSUE TITLE
When load goloadr on goloadr have panic

### ISSUE THREAD

**Issue by nzlov** [dearplain/goloader#13]
[DEMO](https://github.com/nzlov/testgoloader)

## ENV:
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/nzlov/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/nzlov/workspace/go"
GORACE=""
GOROOT="/Users/nzlov/program/go"
GOTMPDIR=""
GOTOOLDIR="/Users/nzlov/program/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/8j/s77lh5993lj9y98_mm7f3mmr0000gn/T/go-build898165777=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

## Run:
```
go tool compile -I $GOPATH/pkg/darwin_amd64/ b1.go
go tool compile -I $GOPATH/pkg/darwin_amd64/ b.go
go run main.go b.o
```

## Panic:
```
unexpected fault address 0x86f2e316a
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x86f2e316a pc=0x100d0bf]

goroutine 1 [running]:
runtime.throw(0x171795a, 0x5)
	/Users/nzlov/program/go/src/runtime/panic.go:616 +0x81 fp=0xc4206ed958 sp=0xc4206ed938 pc=0x102b2d1
runtime.sigpanic()
	/Users/nzlov/program/go/src/runtime/signal_unix.go:395 +0x211 fp=0xc4206ed9a8 sp=0xc4206ed958 pc=0x103fe31
runtime.mapassign_faststr(0x1639c00, 0x86f2e3162, 0xc420295848, 0x8, 0x3)
	/Users/nzlov/program/go/src/runtime/hashmap_fast.go:702 +0x2f fp=0xc4206eda18 sp=0xc4206ed9a8 pc=0x100d0bf
github.com/dearplain/goloader.regTypeInfo(0x86f2e3162, 0x1609e40, 0x17a5f38, 0x82)
	/Users/nzlov/workspace/go/src/github.com/dearplain/goloader/type.go:144 +0x211 fp=0xc4206edac8 sp=0xc4206eda18 pc=0x119efc1
github.com/dearplain/goloader.RegTypes(0x86f2e3162, 0xc4206edcb8, 0x13, 0x13)
	/Users/nzlov/workspace/go/src/github.com/dearplain/goloader/type.go:105 +0xa4 fp=0xc4206edb30 sp=0xc4206edac8 pc=0x119ed34
github.com/dearplain/goloader.RegSymbol(0x86f2e3162)
	/Users/nzlov/workspace/go/src/github.com/dearplain/goloader/register.go:40 +0x408 fp=0xc4206eddf8 sp=0xc4206edb30 pc=0x119e1d8
main.PluginLoad(0xc420095170, 0x1, 0x1, 0xf, 0xc420185d00, 0x1, 0x10125b8, 0x10, 0x160f760)
	/Users/nzlov/workspace/go/src/github.com/nzlov/testgoloader/b.go:26 +0x6c fp=0xc4206ede78 sp=0xc4206eddf8 pc=0x1dd40da
github.com/nzlov/testgoloader/engine.(*Plugin).Load(0xc4200a0180, 0xc42016e8a0, 0xc420095170, 0x1, 0x1, 0x0, 0x0)
	/Users/nzlov/workspace/go/src/github.com/nzlov/testgoloader/engine/engine.go:66 +0x180 fp=0xc4206edee0 sp=0xc4206ede78 pc=0x119fe30
main.reload(0x1694aa0, 0xc4200a0180)
	/Users/nzlov/workspace/go/src/github.com/nzlov/testgoloader/main.go:58 +0x8c fp=0xc4206edf28 sp=0xc4206edee0 pc=0x159f3ec
main.main()
	/Users/nzlov/workspace/go/src/github.com/nzlov/testgoloader/main.go:25 +0x8a fp=0xc4206edf88 sp=0xc4206edf28 pc=0x159f0fa
runtime.main()
	/Users/nzlov/program/go/src/runtime/proc.go:198 +0x212 fp=0xc4206edfe0 sp=0xc4206edf88 pc=0x102cb42
runtime.goexit()
	/Users/nzlov/program/go/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc4206edfe8 sp=0xc4206edfe0 pc=0x1056561
exit status 2
```

**Comment by dearplain** [comment]
1.
global symbol in object file will not init currently, result in panic:
```
var symPtr = map[string]uintptr{}
```
2.
you only need to call below once on loader:
```
goloader.RegSymbol(symPtr)
```

**Comment by nzlov** [comment]
Thanks,It good work.
