### ISSUE TITLE
getitab panic runtime error

### ISSUE THREAD

**Issue by nzlov** [dearplain/goloader#14]
[DEMO](https://github.com/nzlov/testgoloader)

## ENV:
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/nzlov/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/nzlov/workspace/go"
GORACE=""
GOROOT="/Users/nzlov/program/go"
GOTMPDIR=""
GOTOOLDIR="/Users/nzlov/program/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/8j/s77lh5993lj9y98_mm7f3mmr0000gn/T/go-build898165777=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

## Run:
```
go tool compile -I $GOPATH/pkg/darwin_amd64/ a.go
go run main.go a.o
```

## Panic:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x13 pc=0x100eb3f]

goroutine 1 [running]:
github.com/dearplain/goloader.Load(0xc4200c4e00, 0xc4201829f0, 0x0, 0x0, 0x0)
	/Users/nzlov/workspace/go/src/github.com/dearplain/goloader/dymcode.go:503 +0x296c
github.com/nzlov/testgoloader/engine.(*Plugin).Load(0xc4200a0180, 0xc4201829f0, 0xc42029c960, 0x1, 0x1, 0x0, 0x0)
	/Users/nzlov/workspace/go/src/github.com/nzlov/testgoloader/engine/engine.go:55 +0xd9
main.reload(0x1694ae0, 0xc4200a0180)
	/Users/nzlov/workspace/go/src/github.com/nzlov/testgoloader/main.go:59 +0x8c
main.main()
	/Users/nzlov/workspace/go/src/github.com/nzlov/testgoloader/main.go:26 +0xb3
exit status 2
```

**Comment by dearplain** [comment]
add
```
goloader.RegTypes(symPtr, &engine.ErrInitParams{})
```

**Comment by nzlov** [comment]
Ok. Whether the error can remind missing type?

**Comment by dearplain** [comment]
should remind you now.

**Comment by nzlov** [comment]
Yes, It work
