### ISSUE TITLE
Stacktraces result in panic

### ISSUE THREAD

**Issue by dobegor** [dearplain/goloader#9]
Trying to `call debug.PrintStack()` from `runtime/debug` results in runtime panic:
code:
```
func main2(a int) error {
        fmt.Println(a)
        debug.PrintStack()
        return nil
}
```
```
Load error: unresolve external: runtime/debug.PrintStack
unresolve external: runtime/debug.init

322
unexpected fault address 0xc420065f78
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0xc420065f78 pc=0xc420065f78]

goroutine 1 [running]:
runtime.throw(0x1350dcd, 0x5)
	/usr/local/go/src/runtime/panic.go:616 +0x81 fp=0xc420065d68 sp=0xc420065d48 pc=0x102ac11
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:385 +0x273 fp=0xc420065db8 sp=0xc420065d68 pc=0x103f6d3
main.main()
	/Users/dobegor/go/src/github.com/dearplain/goloader/examples/loader/loader.go:75 +0x763 fp=0xc420065f88 sp=0xc420065db8 pc=0x1299863
runtime.main()
	/usr/local/go/src/runtime/proc.go:198 +0x212 fp=0xc420065fe0 sp=0xc420065f88 pc=0x102c482
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc420065fe8 sp=0xc420065fe0 pc=0x1055c01
```

**Comment by dobegor** [comment]
I do understand it's not trivial to support stacktraces in dynamically loaded code, but is it possible with the goloader? Would be a very useful feature to debug plugins loaded by goloader.

**Comment by dearplain** [comment]
There is a load error, please import runtime/debug in your loader first! Goloader cannot resolve symbols which are not existed in .o file or loader.
```
Load error: unresolve external: runtime/debug.PrintStack
unresolve external: runtime/debug.init
```

**Comment by dearplain** [comment]
Goloader supports stacktrace, stack gc scan, goroutine, pprof...

**Comment by dobegor** [comment]
I did import `runtime/debug` as 
```
import (
    _ "runtime/debug"
   // other imports
)```

in loader.go example.

**Comment by dobegor** [comment]
Loader code:
```
package main

import (
	"cmd/objfile/goobj"
	"flag"
	"fmt"
	"net/http"
	"os"
	"reflect"
	"runtime"
	"sync"
	"time"
	"unsafe"
	_ "runtime/debug"

	"github.com/dearplain/goloader"
	"github.com/kr/pretty"
)

func mustOK(err error) {
	if err != nil {
		panic(err)
	}
}

func main() {

	var file = flag.String("o", "", "load go object file")
	var pkgpath = flag.String("p", "main", "package path")
	var parseFile = flag.String("parse", "", "parse go object file")
	var run = flag.String("run", "main.main", "run function")
	var times = flag.Int("times", 1, "run count")

	flag.Parse()

	if *parseFile != "" {
		parse(parseFile, pkgpath)
		return
	}

	if *file == "" {
		flag.PrintDefaults()
		return
	}

	f, err := os.Open(*file)
	if err != nil {
		fmt.Println(err)
		return
	}
	defer f.Close()

	symPtr := make(map[string]uintptr)
	goloader.RegSymbol(symPtr)

	goloader.RegTypes(symPtr, time.Duration(0))
	goloader.RegTypes(symPtr, reflect.ValueOf(0))
	goloader.RegTypes(symPtr, runtime.LockOSThread)
	// most of time you don't need to register function, but if loader complain about it, you have to.
	goloader.RegTypes(symPtr, http.ListenAndServe, http.Dir("/"),
		http.Handler(http.FileServer(http.Dir("/"))), http.FileServer, http.HandleFunc,
		&http.Request{})
	w := sync.WaitGroup{}
	goloader.RegTypes(symPtr, w, w.Wait)

	reloc, _ := goloader.ReadObj(f)

	for i := 0; i < *times; i++ {
		codeModule, err := goloader.Load(reloc, symPtr)
		if err != nil {
			fmt.Println("Load error:", err)
		}
		runFuncPtr := codeModule.Syms[*run]
		funcPtrContainer := (uintptr)(unsafe.Pointer(&runFuncPtr))
		runFunc := *(*func(int)error)(unsafe.Pointer(&funcPtrContainer))
		e := runFunc(322)
		fmt.Println(e)
		codeModule.Unload()
	}

}

func parse(file, pkgpath *string) {

	if *file == "" {
		flag.PrintDefaults()
		return
	}

	f, err := os.Open(*file)
	if err != nil {
		fmt.Printf("%# v\n", err)
		return
	}
	obj, err := goobj.Parse(f, *pkgpath)
	pretty.Printf("%# v\n", obj)
	f.Close()
	if err != nil {
		fmt.Printf("error reading %s: %v\n", *file, err)
		return
	}
}
```

**Comment by dearplain** [comment]
try
```
import "runtime/debug"
goloader.RegTypes(symPtr, debug.PrintStack)
```

**Comment by dearplain** [comment]
most of time you don't need to register function, but if loader complain about it, you have to.
notice load error, if you see any unresovled function or symbol, register it first, most of time, you will only need to register one function in a package, other function in that package will register automatic.

**Comment by dobegor** [comment]
That works great, thanks!
However, I have a question:
Is there any way that can be omitted / made automatically by goloader itself?
Because the common scenario is loading plugins without knowing what packages they will need during their work, and that will result in inability to load some plugin until loader registers a function from package required by plugin.

**Comment by dearplain** [comment]
wait for #6 .

**Comment by dobegor** [comment]
Ok, thanks!
